name: CI (Development Deps)

on:
  push:
    branches:
    - main
    - 'v*'
    tags:
    - '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  allowed_failures:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
    with:
      cache-path: ~/.astropy
      cache-key: ${{ github.ref }}-${{ matrix.toxenv }}-astropycache
      libraries: |
        apt:
          - tzdata
          - libopenblas-base
          - libopenblas-dev
      envs: |
        - name: (Allowed Failure) Python 3.12 with dev version of deps
          linux: py313-test-devdeps-online
          python-version: 3.13-dev

        - name: (Allowed Failure) Python 3.13 with dev version of deps
          linux: py313-test-devdeps-online
          python-version: 3.12

        - macos: py312-test-online
          cache-key: ${{ github.ref }}-py312mac-astropycache

        - windows: py312-test-online
          cache-key: ${{ github.ref }}-py312win-astropycache
