name: CI

on:
  push:
    branches:
    - main
    - 'v*'
    tags:
    - '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ARCH_ON_CI: "normal"
  IS_CRON: "false"

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      setenv: |
        ARCH_ON_CI: "normal"
        IS_CRON: "false"
      submodules: false
      coverage: ''
      libraries: |
        apt:
          - tzdata
      envs: |
        - name: Python 3.8 with old dependencies
          linux: py38-test-olddeps-online

        - name: Python 3.9 with old dependencies
          linux: py39-test-olddeps-online

        - name: Python 3.10 with LTS dependencies
          linux: py310-test-ltsdeps-online

        -name: Python 3.11 with stable deps
          linux: py311-test-stabledeps-online

        -name: Python 3.12 with stable deps
          linux py312-test-stabledeps-online

  allowed_failures:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      setenv: |
        ARCH_ON_CI: "normal"
        IS_CRON: "false"
      submodules: false
      coverage: ''
      libraries: |
        apt:
          - tzdata
      envs: |
        - name: (Allowed Failure) Python 3.12 with remote data and dev version of key dependencies
          linux: py313-test-devdeps
          python-version: 3.13-dev
          posargs: --remote-data=any --verbose

        - name: (Allowed Failure) Python 3.13 with remote data and dev version of key dependencies
          linux: py313-test-devdeps
          python-version: 3.12
          posargs: --remote-data=any --verbose
